version: '3'
services:
  spark-master:
    image: ouail02/spark-node:latest
    container_name: spark-master
    hostname: spark-master
    networks:
      - spark-network
    ports:
      - "8080:8080"
      - "7077:7077"
    expose:
      - "22"
    environment:
      - SPARK_ROLE=master
    command: bash -c "service ssh start && /opt/spark/sbin/start-master.sh"
    
  spark-slave1:
    image: ouail02/spark-node:latest
    container_name: spark-slave1
    hostname: spark-slave1
    networks:
      - spark-network
    expose:
      - "22"
    environment:
      - SPARK_ROLE=slave
    command: bash -c "service ssh start && /opt/spark/sbin/start-slave.sh spark://spark-master:7077"

  spark-slave2:
    image: ouail02/spark-node:latest
    container_name: spark-slave2
    hostname: spark-slave2
    networks:
      - spark-network
    expose:
      - "22"
    environment:
      - SPARK_ROLE=slave
    command: bash -c "service ssh start && /opt/spark/sbin/start-slave.sh spark://spark-master:7077"

 networks:
  spark-network:
    driver: bridge
